---
dex:
  enabled: false

configs:
  params:
    server.insecure: true
  cm:
    url: https://argocd.cereghino.me
    kustomize.buildOptions: "--enable-alpha-plugins --enable-exec"
    oidc.config: |
      name: Dex
      issuer: https://dex.cereghino.me
      clientID: argocd
      clientSecret: $oidc.dex.clientSecret
      requestedScopes:
        - openid
        - email
        - profile
  rbac:
    policy.csv: |
      g, riccardo.cereghino@gmail.com, role:admin
  secret:
    extra:
      oidc.dex.clientSecret: "ccfd06505df7b12d90bf475aa5836cac81ad22b4b5dd979c6d4fc5ddfa12a9f8"

repoServer:
  env:
    - name: XDG_CONFIG_HOME
      value: /.config
    - name: SOPS_AGE_KEY_FILE
      value: /.config/sops/age/keys.txt
  volumes:
    - name: custom-tools
      emptyDir: {}
    - name: sops-age-key
      secret:
        secretName: sops-age-key
  volumeMounts:
    - name: custom-tools
      mountPath: /usr/local/bin/ksops
      subPath: ksops
    - name: custom-tools
      mountPath: /usr/local/bin/kustomize
      subPath: kustomize
    - name: sops-age-key
      mountPath: /.config/sops/age
  initContainers:
    - name: install-ksops
      image: viaductoss/ksops:v4.3.2
      command: ["/bin/sh", "-c"]
      args:
        - |
          cp /usr/local/bin/ksops /custom-tools/ksops &&
          cp /usr/local/bin/kustomize /custom-tools/kustomize
      volumeMounts:
        - name: custom-tools
          mountPath: /custom-tools
