---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
---
apiVersion: v1
kind: Secret
metadata:
  name: dex-secrets
  namespace: auth
type: Opaque
stringData:
  GITHUB_CLIENT_ID: "Ov23lijN3nrCzOfVZSjY"
  GITHUB_CLIENT_SECRET: "41a74debb168de69f32d8040c9fc520eefbeed9b"
  DEX_STATIC_CLIENT_SECRET: "07844409ba0aaf2b007a161d6394456541df8be98d18e97d2792be645d6d3303"
