apiVersion: v1
kind: Namespace
metadata:
    name: auth
sops:
    age:
        - recipient: age1je7fgegf38rae7uxc4gyc4e2qd3d4k6ggchlx4hg2p5tux9ejvvsvyd34y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRlBERlh2WURYalcvSmw2
            bG83ZmgrNXRzV1JDcUs5bGxjVC95aWlaMHpjCkZTb1ZvWHVtNnkya05HS3h4eEFL
            aTJGZzczWFRUODlFTzlJWGgyQ0pwdHcKLS0tIFFhL3paR0RPc2tWTjFNanQ2enQw
            bXVkTlczcG5TNGJicGFCVkp2dWN0SU0KS5kU8Hokpbn5lR9Upy1tKyTif52U7tzW
            wC0gQFxZI5OA5HX9Opz9uoTVTSZ6coEbLXaQysNob9z2u1hUOY9muA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:24:57Z"
    mac: ENC[AES256_GCM,data:CZ5XRgf5HvUXbu1P2m5inVdAkr23tSn1sNj2Hrxz4CJ9somAgPPICj0CwmyBAw95QUA81nYzk4UgAlNqybKDtrD91Ianp1szJe1xyaUCUVjU2CVnQbcV6NF6PzOtlNvVvVjb/PiekaKFrdJckZL54FXSWy9K8VhK4rJ30dFpFEQ=,iv:/6V+p0cu6/oWr0HdR3kPifJsDjgeYv8mozXRGHEZcEQ=,tag:xujQkHxyIEyMtYtA8XujgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
---
apiVersion: v1
kind: Secret
metadata:
    name: dex-secrets
    namespace: auth
type: Opaque
stringData:
    GITHUB_CLIENT_ID: ENC[AES256_GCM,data:fdM04c4N6agxbJJO+b+w0hjsgr8=,iv:SOjwGVbUk4+h251T7KiyCFzhmQG2q4Jezfqj+3AlwDE=,tag:OkHd3DdvtjaGTDF3OsDx9w==,type:str]
    GITHUB_CLIENT_SECRET: ENC[AES256_GCM,data:iGc8qsspMs9yHbn1hPuIPtIjMcQRkFoD+KBraWdhO5Fr47wj2kTjaA==,iv:9dy0xr4o7PnC3EH8OwO8CHS4SNyllSasrLzBDYDWnt8=,tag:tkZmnBJEtRacI8RVGgC8Ag==,type:str]
    DEX_STATIC_CLIENT_SECRET: ENC[AES256_GCM,data:ycCguIWR0xiyZSfLCyRmTbv+djtZXrxx9MJNGR1tUrWFn4w4DdgYLiG9ZHTWOM1sUiHRym+SHRimTO3gIBn8cA==,iv:j/04BGUIdZkao0qrWYpjuB2PWYfqwAekZ19XQKiHp+Q=,tag:08Jm1O7MuWMNfFoUfGrEIQ==,type:str]
sops:
    age:
        - recipient: age1je7fgegf38rae7uxc4gyc4e2qd3d4k6ggchlx4hg2p5tux9ejvvsvyd34y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRlBERlh2WURYalcvSmw2
            bG83ZmgrNXRzV1JDcUs5bGxjVC95aWlaMHpjCkZTb1ZvWHVtNnkya05HS3h4eEFL
            aTJGZzczWFRUODlFTzlJWGgyQ0pwdHcKLS0tIFFhL3paR0RPc2tWTjFNanQ2enQw
            bXVkTlczcG5TNGJicGFCVkp2dWN0SU0KS5kU8Hokpbn5lR9Upy1tKyTif52U7tzW
            wC0gQFxZI5OA5HX9Opz9uoTVTSZ6coEbLXaQysNob9z2u1hUOY9muA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:24:57Z"
    mac: ENC[AES256_GCM,data:CZ5XRgf5HvUXbu1P2m5inVdAkr23tSn1sNj2Hrxz4CJ9somAgPPICj0CwmyBAw95QUA81nYzk4UgAlNqybKDtrD91Ianp1szJe1xyaUCUVjU2CVnQbcV6NF6PzOtlNvVvVjb/PiekaKFrdJckZL54FXSWy9K8VhK4rJ30dFpFEQ=,iv:/6V+p0cu6/oWr0HdR3kPifJsDjgeYv8mozXRGHEZcEQ=,tag:xujQkHxyIEyMtYtA8XujgA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
