apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:vDgnGtk=,iv:vpGp+IbNZQTg7AGtEqJO1h0e085se6tDS34pTGUlSNo=,tag:kyMs4cRkwIJnLoeQpR9DPQ==,type:str]
    admin-password: ENC[AES256_GCM,data:bgNzWLK+UO4LUbnCrw==,iv:Hi1/N4ljgBmRlbW01hZRIdttY3WS4ySY+emN6xVgeXE=,tag:3CeDd4Os4qpKbXCfKqX3gg==,type:str]
sops:
    age:
        - recipient: age1je7fgegf38rae7uxc4gyc4e2qd3d4k6ggchlx4hg2p5tux9ejvvsvyd34y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGTWZWUU9JSDBYQm9SS3li
            K203RStEZzRkYThOL1BKUDFYQzQ3K3EvM3dNCmpXWWsyTThCdXk3Z0k5ajZGbGVG
            M0s2NXlSbG55ZTBxZGVsMEo0Y0pGcWMKLS0tIGp4ZWZTWGVSN1pxMDF2MVpTQTYz
            bnpZNnlkcUFuRFQ2THVyTXpXZ2hRYlEKAkEV/pzzFPuTgQMqiCr0O7BBzz98PFYp
            /5O2L+OT7BMQgJC4t6KV9JMm2CksB0Da2sfd+gPgulZ0qbrZac5G0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:24:58Z"
    mac: ENC[AES256_GCM,data:RugomjqBrMV7XByuB6PspsuXalziYEAXOH0ggMg7HQCC1cJxVyUdwWjJ62aBgT1ad73oxrufYT58oB53CzcsRwZyEmr5dz+Ln9on83sFuS/BtvIfhWs3WPiWO79PtiWQ7xukoHLKL3eiuxdphjep8yMmFBrA4K7ruQJG74V/jxo=,iv:gY5ks/EM5s3bKHgXeB11BVp2PgoxfPHP5nST3S5kOkY=,tag:iixBJaO35erP8t8phkyI8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
