---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secrets
  namespace: kube-system
type: Opaque
stringData:
  client-id: "oauth2-proxy"
  client-secret: "07844409ba0aaf2b007a161d6394456541df8be98d18e97d2792be645d6d3303"
  cookie-secret: "wPkYK9LQ96L1i8P1GQNFJPJ0NpK7FGADSFblT3rt938="
