apiVersion: v1
kind: Secret
metadata:
    name: oauth2-proxy-secrets
    namespace: kube-system
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:cj4tCKrzVJfMwEmI,iv:6OEFVuGl6y7j1K8BuKmfsF6nwgujRxggOykkBFhqnoQ=,tag:3ln1Ltuu4jskRFfdQEpl6Q==,type:str]
    client-secret: ENC[AES256_GCM,data:Vc7rKADJxaqt+MlSsDcXbtcgJuMomnltO8NWRID5TMKkBBrKXDMcUfIDRmXsD02iDZc7Q4MzEMFntrAZUeH5pg==,iv:UQC3fEFO3ssWcvQ6VD2rhv8DwKffAe/QzgTqMLFJRXU=,tag:kRtoP0JP8wPgMU6L6M67nQ==,type:str]
    cookie-secret: ENC[AES256_GCM,data:iP+MNzpwuGp3vh0f5ElYOwuu49hNu871ncNiOlOBnnusl3yWtBip/FaMKkg=,iv:rescgXMSSHMxAFnzrlmVbGC9v7lZy0RTxHXPA9Oo/Iw=,tag:2P4IA045cgLZVJFIOlHaqw==,type:str]
sops:
    age:
        - recipient: age1je7fgegf38rae7uxc4gyc4e2qd3d4k6ggchlx4hg2p5tux9ejvvsvyd34y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQRHFTZTlXKzg2Q0NiNU4v
            UmRqRzhOT2tZS0pMeS9BK1ZrQ0FIdERhNUM0Ck9NeGtuZU93OUdtYWM4eDFDNmRG
            WWtvOG5kY3E1dWhuVThqencrM0JIM1kKLS0tIEtadkZqRGcwL0E2ZlFJcWVBOHlK
            b3lkdndUQVE0TzVMd1YzYTQ0TkhKMWsK0RwQoGjbITAh0unnS/FCekvUpSEzeCE1
            dIxLytah9Hp/DPHE1+E1L3HcQaaqd1rTHBbZRDTF4F5eBQNAx2BrcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:24:58Z"
    mac: ENC[AES256_GCM,data:i88X6h2hGAvB8Z0Gb69GFWbYE+3ASNiJa3qnzBCYSLbp+x2vJ2bw9aQSeI/OWBJi68hqwCukCehjvY9bJ2BKWoyPHyvTKXrYDkJqQzH+yWQmohB54djPdbFRRoZ//7VJL/YlxNyHlhzI9XPZP2BnUrdHR3DGypRo7skg3gKfY64=,iv:EWMvupLncLRJuolHrUP0sLvrxmo6hav4Sm4bWoW9IiY=,tag:sIap4Jcq9ly8bGTzpjR9Zg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
