apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secrets
    namespace: vault
type: Opaque
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:lb2fGxYDQLriT7tYoCvfrL69onBfp9d7u0IpoIIB1DvPxYzret31Vd56bLJtjFlNZEJudiat9l3EboBlQ2ayZveGK3qHg4+BiQVclcD5Pq1GjNO+5dnbgVDZ7MOiNQsQ4A==,iv:V0Xl3Mqa90tB6pdr1aJ5oKL2qskfI1pgUF5ZVCwGR9s=,tag:VWI9cBkOnsAL0w01sT5LQQ==,type:str]
sops:
    age:
        - recipient: age1je7fgegf38rae7uxc4gyc4e2qd3d4k6ggchlx4hg2p5tux9ejvvsvyd34y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYjY3M0FhdkRQRGs1VWFH
            eXEwVXd2MFk1cnpMeUJSL0lzVVI3elExbFFzCkpWUldiNnVlMU1sQlNKcmNUYWpq
            V0k3WUVmOUxMYzJ4bDd0eHY3ajUwbkkKLS0tIHpPVWFCYXlrb0tDWXN3MjRoM1ZC
            U2l6TWt1dENudG55eFlZOXdTdWoreUEKirpwmjLXIXqzs3dtlljFasZEjozdmBOM
            ksVZ9ifASF5UhPxYrc3xn7Sla6r928erpBhJ4H9SJmnCGebqM3PzNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-03T10:24:57Z"
    mac: ENC[AES256_GCM,data:kYac3j63F6kydVkxC6cc3b0ep1kncjLbxD+BGKk0KvXVViv+5m/K5IyjEBpsbpYo+eaQMjHkB2KFy90+PSSQ7M3pswy1NxRbjgX70WUAhCJd2wENp4TO4WMgv0394MhfhC1p7jO1rO5mZBjSbxD1sD33zxEhZZHUKolS2D/kcYk=,iv:wwa/gu6NxxqR5w70DHFHZATFbA9TWvMZPxGhYcqmnKE=,tag:JxLSbPxIRUH6oqEsKNdJCA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
