---
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: vault
type: Opaque
stringData:
  ADMIN_TOKEN: "$argon2id$v=19$m=65536,t=3,p=4$UyY824eCaC9dafiB+XSyGA$mx8QuI20mZDY7Mo+7pMR+gEyX2rtcwbOq4HQPNIKqFU"
