---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-manifests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/RiccardoCereghino/platform-zero.git
    targetRevision: HEAD
    path: platform
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
