---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: velero
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://vmware-tanzu.github.io/helm-charts
    chart: velero
    targetRevision: "*"
    helm:
      valuesObject:
        initContainers:
          - name: velero-plugin-for-aws
            image: velero/velero-plugin-for-aws:v1.9.0
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /target
                name: plugins
        deployNodeAgent: true
        snapshotsEnabled: false
        credentials:
          existingSecret: cloud-credentials
        configuration:
          backupStorageLocation:
            - name: default
              provider: aws
              bucket: cereghino-infra-backups
              prefix: velero
              config:
                region: nbg1
                s3ForcePathStyle: "true"
                s3Url: https://nbg1.your-objectstorage.com
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
