name: Infrastructure CD

on:
  push:
    branches:
      - master
    paths:
      - 'infrastructure/**'

permissions:
  contents: read

jobs:
  infrastructure-cd:
    name: Infrastructure CD
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        working-directory: infrastructure
    env:
      TF_VAR_hcloud_token: ${{ secrets.HCLOUD_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      # This is specifically for the AWS provider (backups)
      TF_VAR_talos_backup_s3_region: ${{ vars.BACKUP_S3_REGION || 'nbg1' }}
      TF_VAR_sops_age_private_key: ${{ secrets.SOPS_AGE_KEY }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest

      - name: Install talosctl
        run: curl -sL https://talos.dev/install | sh

      - name: Tofu Init
        run: |
          tofu init \
            -backend-config="region=${{ vars.STATE_S3_REGION || 'hel1' }}" \
            -backend-config="endpoints={s3=\"https://${{ vars.STATE_S3_REGION || 'hel1' }}.your-objectstorage.com\"}"

      - name: Tofu Apply
        run: tofu apply -auto-approve
